# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew --continue build --parallel

    - name: Upload test results and reports as artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-results-and-reports
        path: |
          **/build/test-results/
          **/build/reports/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml